### ISSUE TITLE
Test compatability with BuddyPress

### ISSUE THREAD

**Issue by userabuser** [JJJ/brutus#2]
> This has not been tested with BuddyPress or bbPress yet. Please submit pull requests if you're able to improve compatibility with these or any other plugins.

**Comment by userabuser** [comment]
@johnjamesjacoby hope you don't mind but I've turned some of the **adverse effects** as listed originally on the main repository page into actual issues.

Unfortunately, I do not have contributor status so I am unable to label the issues appropriately, for example this issue might be a **help wanted** type label. Etc...

**Comment by JJJ** [comment]
@userabuser I don't mind at all, and appreciate it very much.

**Comment by JJJ** [comment]
Works OK. BuddyPress uses WordPress core functions, which Brutus filters normally.
